// <auto-generated />
using System;
using JFS_Task;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JFS_Task.Migrations
{
    [DbContext(typeof(DomainModelPostgreSqlContext))]
    partial class DomainModelPostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JFS_Task.Balance", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<double>("Calculation")
                        .HasColumnType("double precision");

                    b.Property<double>("InBalance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecId");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("JFS_Task.Payment", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentGuid")
                        .HasColumnType("uuid");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.HasKey("RecId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("JFS_Task.TurnoverBalance", b =>
                {
                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Accrued")
                        .HasColumnType("double precision");

                    b.Property<double>("EndingBalance")
                        .HasColumnType("double precision");

                    b.Property<double>("Paid")
                        .HasColumnType("double precision");

                    b.Property<double>("StartingBalance")
                        .HasColumnType("double precision");

                    b.HasKey("Period");

                    b.ToTable("TurnoverBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
